CREATE TABLE SERVIDOR(
	matricula VARCHAR(12) NOT NULL PRIMARY KEY,
    login VARCHAR(50) NOT NULL,
    senha VARCHAR(50) NOT NULL,
    CNH VARCHAR(11) NOT NULL,
    categoria CHAR NOT NULL,
    SIAPE VARCHAR(11) NOT NULL,
    autorizadoVeicInstitucional CHAR,
    CPF VARCHAR(11) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    matSupervisor VARCHAR(12) NOT NULL,
    FOREIGN KEY(matSupervisor) REFERENCES SERVIDOR(matricula)
	ON DELETE CASCADE
    ON UPDATE CASCADE);

