CREATE TABLE SOLICITVEICULO(
	numSolicit INT NOT NULL,
	codVeic VARCHAR(10) NOT NULL,
	PRIMARY KEY(numSolicit, codVeic),
	FOREIGN KEY(numSolicit) REFERENCES SOLICITACAO(numero)
	ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY(codVeic) REFERENCES VEICULO(codigo)
    ON DELETE CASCADE
    ON UPDATE CASCADE);