CREATE TABLE TELEFONE(
	matServ VARCHAR(12) NOT NULL,
    telefone VARCHAR(11) NOT NULL,
    PRIMARY KEY(matServ, telefone),
    FOREIGN KEY(matServ) REFERENCES SERVIDOR(matricula)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
    